[
  {
    _id: "61503b4e47e195788b0a92a4",
    name: "Indian Institute of Technology Madras",
    yearFounded: 1971,
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    noOfStudents: 100,
    coursesOffered: [
      "Computer Science",
      "Electronics",
      "Chemical",
      "Data Science",
    ],
    score: "89.93",
    rank: 1,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92a5",
    name: "Indian Institute of Technology Delhi",
    yearFounded: 1971,
    city: "New Delhi",
    state: "Delhi",
    country: "India",
    noOfStudents: 100,
    coursesOffered: [
      "Computer Science",
      "Electronics",
      "Chemical",
      "Data Science",
    ],
    score: "88.08",
    rank: 2,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92a6",
    name: "Indian Institute of Technology Bombay",
    yearFounded: 1971,
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    noOfStudents: 100,
    coursesOffered: [
      "Computer Science",
      "Electronics",
      "Chemical",
      "Data Science",
    ],
    score: "85.08",
    rank: 3,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92a7",
    name: "Indian Institute of Technology Kanpur",
    yearFounded: 1971,
    city: "Kanpur",
    state: "Uttar Pradesh",
    country: "India",
    noOfStudents: 100,
    coursesOffered: [
      "Computer Science",
      "Electronics",
      "Chemical",
      "Data Science",
    ],
    score: "82.18",
    rank: 4,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92a8",
    name: "Indian Institute of Technology Kharagpur",
    yearFounded: 1971,
    city: "Kharagpur",
    state: "West Bengal",
    country: "India",
    noOfStudents: 100,
    coursesOffered: [
      "Computer Science",
      "Electronics",
      "Chemical",
      "Data Science",
    ],
    score: "80.56",
    rank: 5,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92a9",
    name: "Indian Institute of Technology Roorkee",
    yearFounded: 1971,
    city: "Roorkee",
    state: "Uttarakhand",
    country: "India",
    noOfStudents: 100,
    coursesOffered: [
      "Computer Science",
      "Electronics",
      "Chemical",
      "Data Science",
    ],
    score: "76.29",
    rank: 6,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92aa",
    name: "Indian Institute of Technology Guwahati",
    yearFounded: 1971,
    city: "Guwahati",
    state: "Assam",
    country: "India",
    noOfStudents: 100,
    coursesOffered: [
      "Computer Science",
      "Electronics",
      "Chemical",
      "Data Science",
    ],
    score: "74.9",
    rank: 7,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92ab",
    name: "Indian Institute of Technology Hyderabad",
    yearFounded: 1971,
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    noOfStudents: 100,
    coursesOffered: [
      "Computer Science",
      "Electronics",
      "Chemical",
      "Data Science",
    ],
    score: "66.44",
    rank: 8,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92ac",
    name: "National Institute of Technology Tiruchirappalli",
    yearFounded: 1971,
    city: "Tiruchirappalli",
    state: "Tamil Nadu",
    country: "India",
    noOfStudents: 100,
    coursesOffered: [
      "Computer Science",
      "Electronics",
      "Chemical",
      "Data Science",
    ],
    score: "64.1",
    rank: 9,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92ad",
    name: "Indian Institute of Technology Indore",
    yearFounded: 1971,
    city: "Indore",
    state: "Madhya Pradesh",
    country: "India",
    noOfStudents: 100,
    coursesOffered: [
      "Computer Science",
      "Electronics",
      "Chemical",
      "Data Science",
    ],
    score: "62.88",
    rank: 10,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92ae",
    name: "Indian Institute of Technology (BHU) Varanasi",
    yearFounded: 1971,
    city: "Varanasi",
    state: "Uttar Pradesh",
    country: "India",
    noOfStudents: 100,
    coursesOffered: [
      "Computer Science",
      "Electronics",
      "Chemical",
      "Data Science",
    ],
    score: "62.54",
    rank: 11,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92af",
    name: "Indian Institute of Technology (Indian School of Mines)",
    yearFounded: 1971,
    city: "Dhanbad",
    state: "Jharkhand",
    country: "India",
    noOfStudents: 100,
    coursesOffered: [
      "Computer Science",
      "Electronics",
      "Chemical",
      "Data Science",
    ],
    score: "62.06",
    rank: 12,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92b0",
    name: "National Institute of Technology Karnataka",
    yearFounded: 1971,
    city: "Surathkal",
    state: "Karnataka",
    country: "India",
    noOfStudents: 100,
    coursesOffered: [
      "Computer Science",
      "Electronics",
      "Chemical",
      "Data Science",
    ],
    score: "61.3",
    rank: 13,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92b1",
    name: "Anna University",
    yearFounded: 1971,
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    noOfStudents: 100,
    coursesOffered: [
      "Computer Science",
      "Electronics",
      "Chemical",
      "Data Science",
    ],
    score: "59.89",
    rank: 14,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92b2",
    name: "Vellore Institute of Technology",
    yearFounded: 1971,
    city: "Vellore",
    state: "Tamil Nadu",
    country: "India",
    noOfStudents: 100,
    coursesOffered: [
      "Computer Science",
      "Electronics",
      "Chemical",
      "Data Science",
    ],
    score: "59.32",
    rank: 15,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92b3",
    name: "National Institute of Technology Rourkela",
    yearFounded: 1971,
    city: "Rourkela",
    state: "Odisha",
    country: "India",
    noOfStudents: 100,
    coursesOffered: [
      "Computer Science",
      "Electronics",
      "Chemical",
      "Data Science",
    ],
    score: "59.29",
    rank: 16,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92b4",
    name: "Jadavpur University",
    yearFounded: 1971,
    city: "Kolkata",
    state: "West Bengal",
    country: "India",
    noOfStudents: 100,
    coursesOffered: [
      "Computer Science",
      "Electronics",
      "Chemical",
      "Data Science",
    ],
    score: "59.23",
    rank: 17,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92b5",
    name: "Institute of Chemical Technology",
    yearFounded: 1971,
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    noOfStudents: 100,
    coursesOffered: [
      "Computer Science",
      "Electronics",
      "Chemical",
      "Data Science",
    ],
    score: "58.7",
    rank: 18,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92b6",
    name: "National Institute of Technology Warangal",
    yearFounded: 1971,
    city: "Warangal",
    state: "Telangana",
    country: "India",
    noOfStudents: 100,
    coursesOffered: [
      "Computer Science",
      "Electronics",
      "Chemical",
      "Data Science",
    ],
    score: "57.76",
    rank: 19,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92b7",
    name: "Amrita School of Engineering",
    yearFounded: 1971,
    city: "Amritapuri",
    state: "Kerala",
    country: "India",
    noOfStudents: 100,
    coursesOffered: [
      "Computer Science",
      "Electronics",
      "Chemical",
      "Data Science",
    ],
    score: "57.37",
    rank: 20,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92b8",
    name: "Indian Institute of Engineering Science and Technology",
    yearFounded: 1971,
    city: "Shibpur",
    state: "West Bengal",
    country: "India",
    noOfStudents: 100,
    coursesOffered: [
      "Computer Science",
      "Electronics",
      "Chemical",
      "Data Science",
    ],
    score: "57.14",
    rank: 21,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92b9",
    name: "Indian Institute of Technology Bhubaneswar",
    yearFounded: 1971,
    city: "Bhubaneswar",
    state: "Odisha",
    country: "India",
    noOfStudents: 100,
    coursesOffered: [
      "Computer Science",
      "Electronics",
      "Chemical",
      "Data Science",
    ],
    score: "56.8",
    rank: 22,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92ba",
    name: "National Institute of Technology Calicut",
    yearFounded: 1971,
    city: "Kozhikode",
    state: "Kerala",
    country: "India",
    noOfStudents: 100,
    coursesOffered: [
      "Computer Science",
      "Electronics",
      "Chemical",
      "Data Science",
    ],
    score: "56.56",
    rank: 23,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92bb",
    name: "Indian Institute of Technology Gandhinagar",
    yearFounded: 1971,
    city: "Gandhinagar",
    state: "Gujarat",
    country: "India",
    noOfStudents: 100,
    coursesOffered: [
      "Computer Science",
      "Electronics",
      "Chemical",
      "Data Science",
    ],
    score: "56.15",
    rank: 24,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92bc",
    name: "Indian Institute of Technology Ropar",
    yearFounded: 1971,
    city: "Rupnagar",
    state: "Punjab",
    country: "India",
    noOfStudents: 100,
    coursesOffered: [
      "Computer Science",
      "Electronics",
      "Chemical",
      "Data Science",
    ],
    score: "55.95",
    rank: 25,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92bd",
    name: "Indian Institute of Technology Patna",
    yearFounded: 1971,
    city: "Patna",
    state: "Bihar",
    country: "India",
    noOfStudents: 100,
    coursesOffered: [
      "Computer Science",
      "Electronics",
      "Chemical",
      "Data Science",
    ],
    score: "55.74",
    rank: 26,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92be",
    name: "Visvesvaraya National Institute of Technology",
    yearFounded: 1971,
    city: "Nagpur",
    state: "Maharashtra",
    country: "India",
    noOfStudents: 100,
    coursesOffered: [
      "Computer Science",
      "Electronics",
      "Chemical",
      "Data Science",
    ],
    score: "54.76",
    rank: 27,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92bf",
    name: "Jamia Millia Islamia",
    yearFounded: 1971,
    city: "New Delhi",
    state: "Delhi",
    country: "India",
    noOfStudents: 100,
    coursesOffered: [
      "Computer Science",
      "Electronics",
      "Chemical",
      "Data Science",
    ],
    score: "54.58",
    rank: 28,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92c0",
    name: "Thapar Institute of Engineering &amp; Technology",
    yearFounded: 1971,
    city: "Patiala",
    state: "Punjab",
    country: "India",
    noOfStudents: 100,
    coursesOffered: [
      "Computer Science",
      "Electronics",
      "Chemical",
      "Data Science",
    ],
    score: "54.45",
    rank: 29,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92c1",
    name: "Birla Institute of Technology &amp; Science",
    yearFounded: 1971,
    city: "Pilani",
    state: "Rajasthan",
    country: "India",
    noOfStudents: 100,
    coursesOffered: [
      "Computer Science",
      "Electronics",
      "Chemical",
      "Data Science",
    ],
    score: "54.39",
    rank: 30,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92c2",
    name: "Indian Institute of Technology Mandi",
    yearFounded: 1971,
    city: "Mandi",
    state: "Himachal Pradesh",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "IT", "Civil"],
    score: "54.17",
    rank: 31,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92c3",
    name: "Amity University Noida",
    yearFounded: 1971,
    city: "Gautam Budh Nagar",
    state: "Uttar Pradesh",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "IT", "Civil"],
    score: "53.09",
    rank: 32,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92c4",
    name: "Indian Institute of Space Science and Technology",
    yearFounded: 1971,
    city: "Thiruvananthapuram",
    state: "Kerala",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "IT", "Civil"],
    score: "53.01",
    rank: 33,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92c5",
    name: "Siksha `O` Anusandhan",
    yearFounded: 1971,
    city: "Bhubaneswar",
    state: "Odisha",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "IT", "Civil"],
    score: "52.38",
    rank: 34,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92c6",
    name: "Malaviya National Institute of Technology",
    yearFounded: 1971,
    city: "Jaipur",
    state: "Rajasthan",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "IT", "Civil"],
    score: "52.25",
    rank: 35,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92c7",
    name: "Delhi Technological University",
    yearFounded: 1971,
    city: "New Delhi",
    state: "Delhi",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "IT", "Civil"],
    score: "51.99",
    rank: 36,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92c8",
    name: "Shanmugha Arts Science Technology &amp; Research Academy",
    yearFounded: 1971,
    city: "Thanjavur",
    state: "Tamil Nadu",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "IT", "Civil"],
    score: "51.79",
    rank: 37,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92c9",
    name: "Birla Institute of Technology",
    yearFounded: 1971,
    city: "Ranchi",
    state: "Jharkhand",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "IT", "Civil"],
    score: "51.42",
    rank: 38,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92cb",
    name: "National Institute of Technology Kurukshetra",
    yearFounded: 1971,
    city: "Kurukshetra",
    state: "Haryana",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "IT", "Civil"],
    score: "51.19",
    rank: 39,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92ca",
    name: "Aligarh Muslim University",
    yearFounded: 1971,
    city: "Aligarh",
    state: "Uttar Pradesh",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "IT", "Civil"],
    score: "51.39",
    rank: 39,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92cc",
    name: "S. R. M. Institute of Science and Technology",
    yearFounded: 1971,
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "IT", "Civil"],
    score: "50.95",
    rank: 41,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92cd",
    name: "Kalinga Institute of Industrial Technology",
    yearFounded: 1971,
    city: "Bhubaneswar",
    state: "Odisha",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "IT", "Civil"],
    score: "50.07",
    rank: 42,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92ce",
    name: "International Institute of Information Technology Hyderabad",
    yearFounded: 1971,
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "IT", "Civil"],
    score: "49.45",
    rank: 43,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92cf",
    name: "Sri Sivasubramaniya Nadar College of Engineering",
    yearFounded: 1971,
    city: "Kancheepuram",
    state: "Tamil Nadu",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "IT", "Civil"],
    score: "49.26",
    rank: 44,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92d0",
    name: "Manipal Institute of Technology",
    yearFounded: 1971,
    city: "Manipal",
    state: "Karnataka",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "IT", "Civil"],
    score: "49.06",
    rank: 45,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92d1",
    name: "National Institute of Technology Silchar",
    yearFounded: 1971,
    city: "Silchar",
    state: "Assam",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "IT", "Civil"],
    score: "48.66",
    rank: 46,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92d2",
    name: "National Institute of Technology Durgapur",
    yearFounded: 1971,
    city: "Durgapur",
    state: "West Bengal",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "IT", "Civil"],
    score: "48.39",
    rank: 47,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92d3",
    name: "Motilal Nehru National Institute of Technology",
    yearFounded: 1971,
    city: "Allahabad",
    state: "Uttar Pradesh",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "IT", "Civil"],
    score: "48.24",
    rank: 48,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92d4",
    name: "PSG College of Technology",
    yearFounded: 1971,
    city: "Coimbatore",
    state: "Tamil Nadu",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "IT", "Civil"],
    score: "47.21",
    rank: 49,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92d5",
    name: "College of Engineering Pune",
    yearFounded: 1971,
    city: "Pune",
    state: "Maharashtra",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "IT", "Civil"],
    score: "46.79",
    rank: 50,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92d6",
    name: "Sathyabama Institute of Science and Technology",
    yearFounded: 1971,
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "IT", "Civil"],
    score: "46.77",
    rank: 51,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92d7",
    name: "Dr. B. R. Ambedkar National Institute of Technology",
    yearFounded: 1971,
    city: "Jalandhar",
    state: "Punjab",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "IT", "Civil"],
    score: "46.45",
    rank: 52,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92d8",
    name: "Indian Institute of Technology Jodhpur",
    yearFounded: 1971,
    city: "Jodhpur",
    state: "Rajasthan",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "IT", "Civil"],
    score: "46.13",
    rank: 53,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92d9",
    name: "Sardar Vallabhbhai National Institute of Technology",
    yearFounded: 1971,
    city: "Surat",
    state: "Gujarat",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "IT", "Civil"],
    score: "45.59",
    rank: 54,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92da",
    name: "Visvesvaraya Technological University",
    yearFounded: 1971,
    city: "Belgaum",
    state: "Karnataka",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "IT", "Civil"],
    score: "45.37",
    rank: 55,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92db",
    name: "Indraprastha Institute of Information Technology Delhi",
    yearFounded: 1971,
    city: "New Delhi",
    state: "Delhi",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "IT", "Civil"],
    score: "45.03",
    rank: 56,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92dc",
    name: "Jawaharlal Nehru Technological University",
    yearFounded: 1971,
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "IT", "Civil"],
    score: "44.97",
    rank: 57,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92dd",
    name: "Koneru Lakshmaiah Education Foundation University",
    yearFounded: 1971,
    city: "Vaddeswaram",
    state: "Andhra Pradesh",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "IT", "Civil"],
    score: "44.7",
    rank: 58,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92de",
    name: "M. S. Ramaiah Institute of Technology",
    yearFounded: 1971,
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "IT", "Civil"],
    score: "43.74",
    rank: 59,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92df",
    name: "Kalasalingam Academy of Research and Higher Education",
    yearFounded: 1971,
    city: "Srivilliputtur",
    state: "Tamil Nadu",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "IT", "Civil"],
    score: "43.71",
    rank: 60,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92e0",
    name: "National Institute of Technology Meghalaya",
    yearFounded: 1971,
    city: "Shillong",
    state: "Meghalaya",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "Mechanical", "Civil"],
    score: "43.69",
    rank: 61,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92e1",
    name: "International Institute of Information Technology Bangalore",
    yearFounded: 1971,
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "Mechanical", "Civil"],
    score: "43.55",
    rank: 62,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92e2",
    name: "Defence Institute of Advanced Technology",
    yearFounded: 1971,
    city: "Pune",
    state: "Maharashtra",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "Mechanical", "Civil"],
    score: "43.13",
    rank: 63,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92e3",
    name: "Thiagarajar College of Engineering",
    yearFounded: 1971,
    city: "Madurai",
    state: "Tamil Nadu",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "Mechanical", "Civil"],
    score: "43.11",
    rank: 64,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92e4",
    name: "Maulana Azad National Institute of Technology",
    yearFounded: 1971,
    city: "Bhopal",
    state: "Madhya Pradesh",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "Mechanical", "Civil"],
    score: "42.17",
    rank: 65,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92e5",
    name: "Indian Institute of Information Technology Guwahati",
    yearFounded: 1971,
    city: "Guwahati",
    state: "Assam",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "Mechanical", "Civil"],
    score: "41.92",
    rank: 66,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92e6",
    name: "National Institute of Technology Raipur",
    yearFounded: 1971,
    city: "Raipur",
    state: "Chhattisgarh",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "Mechanical", "Civil"],
    score: "41.58",
    rank: 67,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92e7",
    name: "Punjab Engineering College (Deemed To Be University)",
    yearFounded: 1971,
    city: "Chandigarh",
    state: "Chandigarh",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "Mechanical", "Civil"],
    score: "41.43",
    rank: 68,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92e8",
    name: "College of Engineering(A)",
    yearFounded: 1971,
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "Mechanical", "Civil"],
    score: "41.36",
    rank: 69,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92e9",
    name: "R. V. College of Engineering",
    yearFounded: 1971,
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "Mechanical", "Civil"],
    score: "41.02",
    rank: 70,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92ea",
    name: "Veermata Jijabai Technological Institute",
    yearFounded: 1971,
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "Mechanical", "Civil"],
    score: "40.58",
    rank: 71,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92eb",
    name: "Panjab University",
    yearFounded: 1971,
    city: "Chandigarh",
    state: "Chandigarh",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "Mechanical", "Civil"],
    score: "40.44",
    rank: 72,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92ec",
    name: "B.M.S. College of Engineering",
    yearFounded: 1971,
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "Mechanical", "Civil"],
    score: "40.35",
    rank: 73,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92ed",
    name: "Indian Institute of Food Processing Technology (IIFPT)",
    yearFounded: 1971,
    city: "Thanjavur",
    state: "Tamil Nadu",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "Mechanical", "Civil"],
    score: "40.24",
    rank: 74,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92ee",
    name: "National Institute of Technology Agartala",
    yearFounded: 1971,
    city: "Agratala",
    state: "Tripura",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "Mechanical", "Civil"],
    score: "39.98",
    rank: 75,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92ef",
    name: "Netaji Subhas University of Technology (NSUT)",
    yearFounded: 1971,
    city: "South West",
    state: "Delhi",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "Mechanical", "Civil"],
    score: "39.97",
    rank: 76,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92f0",
    name: "National Institute of Technology Goa",
    yearFounded: 1971,
    city: "Ponda",
    state: "Goa",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "Mechanical", "Civil"],
    score: "39.93",
    rank: 77,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92f1",
    name: "Shri Mata Vaishno Devi University",
    yearFounded: 1971,
    city: "Katra",
    state: "Jammu and Kashmir",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "Mechanical", "Civil"],
    score: "39.68",
    rank: 78,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92f2",
    name: "National Institute of Technology Jamshedpur",
    yearFounded: 1971,
    city: "Jamshedpur",
    state: "Jharkhand",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "Mechanical", "Civil"],
    score: "39.44",
    rank: 79,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92f3",
    name: "Karunya Institute of Technology and Sciences",
    yearFounded: 1971,
    city: "Coimbatore",
    state: "Tamil Nadu",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "Mechanical", "Civil"],
    score: "39.4",
    rank: 80,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92f4",
    name: "Indian Institute of Information Technology Design &amp; Manufacturing Jabalpur",
    yearFounded: 1971,
    city: "Jabalpur",
    state: "Madhya Pradesh",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "Mechanical", "Civil"],
    score: "39.29",
    rank: 81,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92f5",
    name: "Kumaraguru College of Technology",
    yearFounded: 1971,
    city: "Coimbatore",
    state: "Tamil Nadu",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "Mechanical", "Civil"],
    score: "39.24",
    rank: 82,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92f6",
    name: "Sri Krishna College of Engineering and Technology",
    yearFounded: 1971,
    city: "Coimbatore",
    state: "Tamil Nadu",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "Mechanical", "Civil"],
    score: "38.83",
    rank: 83,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92f7",
    name: "Chandigarh University",
    yearFounded: 1971,
    city: "Mohali",
    state: "Punjab",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "Mechanical", "Civil"],
    score: "38.82",
    rank: 84,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92f8",
    name: "College of Engineering Trivandrum",
    yearFounded: 1971,
    city: "Thiruvananthapuram",
    state: "Kerala",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "Mechanical", "Civil"],
    score: "38.68",
    rank: 85,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92f9",
    name: "Guru Gobind Singh Indraprastha University",
    yearFounded: 1971,
    city: "New Delhi",
    state: "Delhi",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "Mechanical", "Civil"],
    score: "38.61",
    rank: 86,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92fa",
    name: "Lovely Professional University",
    yearFounded: 1971,
    city: "Phagwara",
    state: "Punjab",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "Mechanical", "Civil"],
    score: "38.44",
    rank: 87,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92fb",
    name: "University College of Engineering",
    yearFounded: 1971,
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "Mechanical", "Civil"],
    score: "38.43",
    rank: 88,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92fc",
    name: "Graphic Era University",
    yearFounded: 1971,
    city: "Dehradun",
    state: "Uttarakhand",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "Mechanical", "Civil"],
    score: "38.32",
    rank: 89,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92fd",
    name: "Coimbatore Institute of Technology",
    yearFounded: 1971,
    city: "Coimbatore",
    state: "Tamil Nadu",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Computer Science", "Electronics", "Mechanical", "Civil"],
    score: "38.24",
    rank: 90,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92fe",
    name: "Siddaganga Institute of Technology",
    yearFounded: 1971,
    city: "Tumkur",
    state: "Karnataka",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Bio Tech", "AI", "Aerospace", "Civil"],
    score: "38.23",
    rank: 91,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a92ff",
    name: "National Institute of Technology Patna",
    yearFounded: 1971,
    city: "Patna",
    state: "Bihar",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Bio Tech", "AI", "Aerospace", "Civil"],
    score: "38.21",
    rank: 92,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a9300",
    name: "C.V. Raman Global University",
    yearFounded: 1971,
    city: "Bhubaneswar",
    state: "Odisha",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Bio Tech", "AI", "Aerospace", "Civil"],
    score: "37.94",
    rank: 93,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a9301",
    name: "PES University",
    yearFounded: 1971,
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Bio Tech", "AI", "Aerospace", "Civil"],
    score: "37.94",
    rank: 93,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a9302",
    name: "Vel Tech Rangarajan Dr. Sagunthala R &amp; D Institute of Science and Technology",
    yearFounded: 1971,
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Bio Tech", "AI", "Aerospace", "Civil"],
    score: "37.86",
    rank: 95,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a9303",
    name: "Jaypee Institute of Information Technology",
    yearFounded: 1971,
    city: "Noida",
    state: "Uttar Pradesh",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Bio Tech", "AI", "Aerospace", "Civil"],
    score: "37.8",
    rank: 96,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a9304",
    name: "University College of Engineering",
    yearFounded: 1971,
    city: "Kakinada",
    state: "Andhra Pradesh",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Bio Tech", "AI", "Aerospace", "Civil"],
    score: "37.77",
    rank: 97,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a9305",
    name: "National Institute of Technology Hamirpur",
    yearFounded: 1971,
    city: "Hamirpur",
    state: "Himachal Pradesh",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Bio Tech", "AI", "Aerospace", "Civil"],
    score: "37.73",
    rank: 98,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a9306",
    name: "Bharati Vidyapeeth Deemed University College of Engineering",
    yearFounded: 1971,
    city: "Pune",
    state: "Maharashtra",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Bio Tech", "AI", "Aerospace", "Civil"],
    score: "37.71",
    rank: 99,
    __v: 0,
  },
  {
    _id: "61503b4e47e195788b0a9307",
    name: "Atal Bihari Vajpayee Indian Institute of Information Technology and Management",
    yearFounded: 1971,
    city: "Gwalior",
    state: "Madhya Pradesh",
    country: "India",
    noOfStudents: 100,
    coursesOffered: ["Bio Tech", "AI", "Aerospace", "Civil"],
    score: "37.6",
    rank: 100,
    __v: 0,
  },
];
